app = "adrianplavka-protohackers"
kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[env]

[[services]]
  internal_port = 5000
  processes = ["app"]
  protocol = "udp"

  [[services.ports]]
    port = "5000"
